linearlabs-workspace/storybook-addon-mock

package.json, yarn.lock
=> fix: immer vulnerability

README.md
Fixes #18 
Add a Storybook v6 example, in contrast with the older version example.
=> Add modernized example to Readme

package.json, yarn.lock
=> chore: move react react-dom from peer to dev dependencies

package.json, src/components/Field/index.js, src/components/RequestItem/index.js, src/utils/array.js, src/utils/faker.js, src/utils/faker.test.js
=> feat: support query params in the URL path and fix console warnings

src/utils/faker.js, src/utils/faker.test.js
=> fix: support relative path in the url

src/components/RequestItem/index.js
Fails when response it not an object
=> Support an array as response

README.md, src/components/RequestItem/index.js, src/components/RequestItem/styled.js, src/manager.js, src/utils/faker.js, src/utils/faker.test.js, stories/example.stories.js
=> Support delaying response

package.json, src/components/Field/index.js, src/components/Field/styled.js, src/components/PlayButton/index.js, src/components/PlayButton/styled.js, src/components/RequestItem/index.js, src/components/RequestItem/styled.js, stories/example.stories.js, yarn.lock
=> Fix: New UI look with delay option

src/index.js, src/manager.js
=> fix: pass parameters as object

src/utils/faker.js
fixes https://github.com/nutboltu/storybook-addon-mock/issues/64
=> Fix: Multiple mocks in story - when default GET

src/components/RequestItem/index.js, src/manager.js, src/utils/faker.js, src/utils/faker.test.js, stories/example.stories.js
=> feat: add ignore url params option

src/components/RequestItem/index.js, src/manager.js, src/utils/faker.js, src/utils/faker.test.js, stories/example.stories.js
This reverts commit dbbe3f026e31f4a7dbe91ca64462c7197a9af2f4.
as per this comment https://github.com/nutboltu/storybook-addon-mock/issues/78#issuecomment-1001250426
=> Revert "feat: add ignore url params option"

src/components/Field/index.js
=> style: add word-break

package.json
=> fix: add support for react 18

.nvmrc, package.json, src/utils/faker.js, src/utils/response.js, stories/components/get-request/index.js, stories/components/non-get-request/index.js, stories/example.stories.js, stories/utils/index.js, yarn.lock
=> feat: add header support for response

packages/mock-addon-docs/stories/docs/advanced-setup.stories.mdx, packages/mock-addon/src/preset/manager.js
=> feat: add disable feature in the panel

packages/mock-addon/package.json
=> chore: add polished as dependencies

packages/mock-addon/src/Panel.js, packages/mock-addon/src/components/MockItem/index.js, packages/mock-addon/src/withRoundTrip.js
=> fix: disableUsingOriginal bug

packages/mock-addon/package.json
=> chore: add prop-types as dependencies

packages/mock-addon/package.json, packages/mock-addon/src/utils/faker.js, packages/mock-addon/src/utils/response.js, packages/mock-addon/src/utils/response.test.js, yarn.lock
=> fix: replace Response function with the JS Response class
